// API actionTypes
export const USER_LOGIN_START = 'USER_LOGIN_START'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

export const USER_LOGGED_OUT_SUCCESS = 'USER_LOGGED_OUT_SUCCESS'
export const USER_LOGGED_OUT_FAILURE = 'USER_LOGGED_OUT_FAILURE'

export const USER_SIGNUP_START = 'USER_SIGNUP_START'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE'

export const LOGIN_CONFIRM_START = 'LOGIN_CONFIRM_START'
export const LOGIN_CONFIRM_SUCCESS = 'LOGIN_CONFIRM_SUCCESS'
export const LOGIN_CONFIRM_FAILURE = 'LOGIN_CONFIRM_FAILURE'

export const VALIDATE_TOKEN_START = 'VALIDATE_TOKEN_START'
export const VALIDATE_TOKEN_SUCCESS = 'VALIDATE_TOKEN_SUCCESS'
export const VALIDATE_TOKEN_FAILURE = 'VALIDATE_TOKEN_FAILURE'

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE'

export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE'

export const ADD_ACCOUT_START = 'ADD_ACCOUT_START'
export const ADD_ACCOUT_SUCCESS = 'ADD_ACCOUT_SUCCESS'
export const ADD_ACCOUT_FAILURE = 'ADD_ACCOUT_FAILURE'

export const FETCH_USER_START = 'FETCH_USER_START'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'

export const FETCH_RATING_START = 'FETCH_RATING_START'
export const FETCH_RATING_SUCCESS = 'FETCH_RATING_SUCCESS'
export const FETCH_RATING_FAILURE = 'FETCH_RATING_FAILURE'

export const ADD_SR = 'ADD_SR'
export const UPDATE_SR = 'UPDATE_SR'
export const DELETE_SR = 'DELETE_SR'

// App actionTypes

export const GO_TO_SIGNIN_FORM = 'GO_TO_SIGNIN_FORM'
export const GO_TO_SIGNUP_FORM = 'GO_TO_SIGNUP_FORM'
export const GO_TO_USER_PAGE = 'GO_TO_USER_PAGE'
