export const FETCH_USER_START = 'FETCH_USER_START'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'

export const FETCH_RATING_START = 'FETCH_RATING_START'
export const FETCH_RATING_SUCCESS = 'FETCH_RATING_SUCCESS'
export const FETCH_RATING_FAILURE = 'FETCH_RATING_FAILURE'

export const ADD_SR = 'ADD_SR'
export const UPDATE_SR = 'UPDATE_SR'
export const DELETE_SR = 'DELETE_SR'

export const GO_TO_USER_PAGE = 'GO_TO_USER_PAGE'
